### ISSUE TITLE
Covalent server returns HTTP 500 Internal Server Error when submitting a workflow

### ISSUE THREAD

**Issue by Emmanuel289** [AgnostiqHQ/covalent#689] opened 2022-06-20 19:59 UTC
### Environment

- **Covalent version**:  0.106.0
- **Python version**: 3.8.13
- **Operating system**: Linux/MacOS

### What is happening?

Covalent server returns HTTP 500 Internal Server Error when submitting a workflow, even while 
other workflows can be submitted.

### How can we reproduce the issue?

This is a rare event that occurs when a batch of workflows on the order of ~10-20 jobs have been submitted to the Covalent server and a new workflow is submitted in succession.  

### What should happen?

Covalent server should consistently be able to pick up submitted/resubmitted workflows and return useful debugging information that may arise from exceptions or validation errors.

**Comment by scottwn** [comment] 2022-07-14 20:56
For 2 and 5, please link to the issues that are tracking these fixes.

For 3 and 4, are these things that can be fixed? Do we have a plan for them?

**Comment by wjcunningham7** [comment] 2022-07-15 16:25
for 2 and 5 I want to come back to them after the switch to FastAPI, and after the db changes are integrated with the front-end.

for 3 and 4, they only occur when I'm testing using >500 users on my machine.

**Comment by scottwn** [comment] 2022-07-15 20:17
Feedback from @venkatBala : 
`database is locked` is caused by multiple threads attempting to write to the DB concurrently. These may need to be queued.

**Comment by scottwn** [comment] 2022-07-15 20:25
One convincing theory from @venkatBala is that @wjcunningham7 sees the errors at ~500 workflows and @Emmanuel289 sees the errors at ~20 workflows because @wjcunningham7 server has much better specs. In order to close this we need to decide what threshold of of workflows must be supported on what type of machine, and ensure that it will run without error.

**Comment by wjcunningham7** [comment] 2022-07-17 21:13
@scottwn I think we should publish expected behavior for standard user configs, e.g., 4cores/8GB, 8cores/16GB for now.  Would also be nice to identify the minimal specs to run Covalent as 1 user.  We can use VMs to test whether these errors appear on these servers for certain workloads, e.g., X concurrent users with 1 workflow, or batches of Y workflows from 1 user.  Ideal output is a few configurations for using Covalent that we can add to the docs.

**Comment by Emmanuel289** [comment] 2022-07-18 22:40
I did a retrial on my 8-core, 32GB mac with Covalent v135.0,  dispatching up to 27 jobs in succession with workflows containing O(100) electrons and I did not get the original 500 error. However, the UI froze indefinitely and the db became locked.

**Comment by cjao** [comment] 2022-11-20 11:39
Does this still happen?

**Closed** 2023-02-13 02:28 UTC
Labels: bug, good first issue, covalent-os, Team East
