### ISSUE TITLE
queue consumer issue with nats server during a workflow

### ISSUE THREAD

**Issue by venkatBala** [AgnostiqHQ/covalent#379] opened 2022-04-14 21:37 UTC
/covalent-slurm/lib/python3.8/site-packages/nats/aio/client.py", line 1138, in _select_next_server
    r, w = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/usr/lib/python3.8/asyncio/streams.py", line 52, in open_connection
    transport, _ = await loop.create_connection(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 4222)

**Comment by AlejandroEsquivel** [comment] 2022-04-20 17:50
@venkatBala is there a particular scenario in which this is observed or any steps to reproduce?

**Comment by AlejandroEsquivel** [comment] 2022-05-26 19:28
Closing due to NATS being removed from codebase. Issue was likely a race condition, prior to proper nats client retry configuration.

**Closed by AlejandroEsquivel** 2022-05-26 19:28 UTC
Labels: bug, priority / high, cloud
