### ISSUE TITLE
append() call causes attribute errors

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#760] opened 2022-07-02 22:01 UTC
### Environment

- **Covalent version**: `0.118.0`
- **Python version**: Python 3.8.13
- **Operating system**: MacOS 12.4

### What is happening?

A call to `list.append()` is causing attribute errors in `electron.py` related to the fact that the `function` attribute is set to `None`

### How can we reproduce the issue?

```
@ct.electron
def say_hello():
    print("hello")
    return "hello"


@ct.electron
def say_all(a):
    for word in a:
        print(a)
    return a[:1]


@ct.lattice
def outputs(a, b, c):
    x = say_hello()
    y = say_all([a, b, c, say_hello(), "world"])
    y.append(x)
    return y

dispatch_id = ct.dispatch(outputs)(8,9,10)
result = ct.get_result(dispatch_id)
```

### What should happen?

I expect the dispatch to run successfully. The outputs, which should be stored in node stdout and the result, are
```
>>> import covalent as ct
>>> @ct.electron
... def say_hello():
...     print("hello")
...     return "hello"
...
>>>
>>> @ct.electron
... def say_all(a):
...     for word in a:
...         print(a)
...     return a[:1]
...
>>>
>>> @ct.lattice
... def outputs(a, b, c):
...     x = say_hello()
...     y = say_all([a, b, c, say_hello(), "world"])
...     y.append(x)
...     return y
...
>>> print(outputs(8,9,10))
hello
hello
[8, 9, 10, 'hello', 'world']
[8, 9, 10, 'hello', 'world']
[8, 9, 10, 'hello', 'world']
[8, 9, 10, 'hello', 'world']
[8, 9, 10, 'hello', 'world']
[8, 'hello']
```

**Comment by santoshkumarradha** [comment] 2022-07-03 00:20
Hey @scottwn  actually this is not a bug, but rather a feature ask. We only support limited set of things that a user can do inside a lattice. This is because, whats inside lattice is used to build a graph and we need to know whats being executed. So lattice is almost like a mini compiler of sorts. In your case, when building the lattice, there is no way for us to know that `y` return type is going to be list to which one can append. Same is true for operations like addition/subtraction etc.. but we have overrided these options at object level.  

But this might be a good feature to solve for !

**Comment by santoshkumarradha** [comment] 2022-07-03 00:22
PS: this should work tho
```python

@ct.lattice
def function():
  a=[]
  a.append(some_electron())
  return a
```
this is because here, a is not an electron and thus can be handled in post process function.

**Comment by santoshkumarradha** [comment] 2022-07-03 00:30
Actually thinking about it, even despite that, we have overwrited `getattr` so in theory this should work. @kessler-frost  thoughts ?

**Comment by scottwn** [comment] 2022-07-03 14:40
Yeah I was thinking that I might have needed to wrap `append` in it's own user defined electron to get it to work. But even so, I don't think the attribute error is expected. Maybe we just need better error handling to let the user know when they've done something illegal in a lattice?

**Comment by kessler-frost** [comment] 2022-07-04 17:30
@santoshkumarradha So in this case, the problem is that `append` is being used as a callable and not as an attribute. So these things are valid:
```python
a.append[some_electron()] # 1
a.append[2] # 2

# but this is not
a.append(some_electron()) # 3
```
That said, there is an issue which was recently discovered and addressed in PR https://github.com/AgnostiqHQ/covalent/pull/754 where even `#1` wasn't working in some cases.

For @scottwn 's comment, yes we should convey it better to the user on when they are doing something illegal, but I'm not sure how 🤔 .

**Comment by cjao** [comment] 2022-07-04 20:30
Even the patch in #754 wouldn't help here. All I do there is replace `Electron.__getattr__` with [the user-defined electron](https://github.com/AgnostiqHQ/covalent/pull/754/files#diff-19420ec90ca8d41f533ddfd395a0af8c44b23b1a067cc04cf0968d518de42108R261) 
```python
@ct.electron
def getattr(e, attr):
  return getattr(e, attr)
```
That works unless attr is a callable; in that case, Covalent has no way to inspect the signature of the callable during `build_graph` and therefore cannot establish the relationships between the callable and its inputs.

At the risk of tooting my own horn, the incremental `build_graph` suggested in #761 might help here. By making `Electron.__getattr__` immediately send the partially built graph and wait for the result, in this line
```
    y.append(x)
```
`build_graph` would first resolve `y` into a list, and then invoke `append(x)` on that list.

**Comment by cjao** [comment] 2022-07-04 20:49
For the time being, I agree with @scottwn that the defining a custom electron like
```python
def append(array, x):
    return array.append(x)
```
would be a workaround. However, this would be inefficient (quadratic with the number of append calls) since since such an electron wouldn't be able to manipulate external data structures in-place like `list.append()` normally does, so we must return a new array every time append is called.

**Comment by cjao** [comment] 2022-07-08 19:21
A related problem is that we currently don't support Electrons that return a Callable.

**Closed** 2023-08-31 21:24 UTC
Labels: bug
