### ISSUE TITLE
Deletion of Workflows

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#1207] opened 2022-09-13 01:32 UTC
## Overview

- Move the logic of workflow deletion logic `covalent_ui/api/v1/data_layer/summary_dal.py:delete_dispatches` to a `delete_workfow` function located in covalent dispatcher
- The workflow deletion logic should be reviewed to ensure it is sound and exposed as an API endpoint DELETE `/api/result/:dispatch_id` in covalent_dispatcher that invokes the above method
- A separate `delete` method should be exposed by the SDK that calls the above endpoint 
- Update UI to call the above endpoint

**Comment by kessler-frost** [comment] 2023-12-04 15:41
Duplicate of #1217

**Closed by kessler-frost** 2023-12-04 15:41 UTC
Labels: Epic, Team West
