### ISSUE TITLE
Runtime in UI can be inaccurate before completion

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [AgnostiqHQ/covalent#1636] opened 2023-05-09 07:14 UTC
### Environment

- **Covalent version**: 0.220.0
- **Python version**: 3.9.16 (in a miniconda env) 
- **Operating system**: Ubuntu (WSL)

### What is happening?

The runtime in the UI is inaccurate until the job completes or fails.

### How can we reproduce the issue?

1. Install Covalent
2. Start the server
3. Open an IPython terminal (or Jupyter Notebook)
4. Wait for a minute or two
5. Run a sample workflow like the one below
6. Check the UI

```python
import covalent as ct
import time

@ct.lattice
@ct.electron
def add(val1,val2):
    time.sleep(30)
    return val1+val2

dispatch_id = ct.dispatch(add)(1,2)
result = ct.get_result(dispatch_id)
```

During runtime:
<img width="321" alt="image" src="https://user-images.githubusercontent.com/8674072/237021813-f7537800-009d-4124-80fb-53ae9715d1cf.png">

After runtime:
<img width="319" alt="image" src="https://user-images.githubusercontent.com/8674072/237021892-b9b1622e-89a6-4fe0-93f8-f81ac580ba0e.png">

### What should happen?

The runtime should reflect the runtime since dispatch.

### Any suggestions?

At first, I thought this might be the same issue as #1420, but that was specifically the total dispatch duration, which is different (for me, the total dispatch duration appears just fine so maybe that prior issue can be closed).

¯\\_(ツ)_/¯

**Comment by madhur-tandon** [comment] 2023-05-11 00:56
@arosen93 I wasn't able to reproduce this. But then, I am using the version of covalent which is the current `develop` branch on Github i.e. it is not a released version.

I am on a Mac with Python 3.9.16 installed via Mambaforge

Perhaps the fix is present in the current state of the repository and simply hasn't been released yet...

Maybe @santoshkumarradha, @kessler-frost or perhaps @AlejandroEsquivel could confirm further...

**Comment by arosen93** [comment] 2023-05-15 17:39
I'm closing this for now because updating to the `develop` branch _seems_ to have solved it, but I'll reopen it if it reappears!

**Comment by arosen93** [comment] 2023-05-20 22:54
I'm re-opening this because for me the issue still exists when using `pip install covalent --pre`. Interestingly, the runtime in my Jupyter Notebook _also_ shows an unusually large value, and this value matches that in the UI. 

For instance, I'll restart the kernel and run the cell, and it'll show 1 hr 45 minutes while running then bump down to the correct value (e.g. 10 s) when it's done. So, the UI is matching what's in my Jupyter Notebook, but the Jupyter Notebook is not correct...

**Comment by santoshkumarradha** [comment] 2023-05-23 12:33
@Prasy12 I remember we faced this when hosting in remote VM as time zone had been hardcoded, but I thought this was fixed, can you take a look at this ?

**Comment by jimmylism** [comment] 2023-12-15 15:53
@Andrew-S-Rosen do you still see this issue? I believe when trying it out on my end, this seems to have been fixed. Lmk either way, thanks!

**Closed** 2023-12-15 15:55 UTC
Labels: bug, priority / low

**Comment by Andrew-S-Rosen** [comment] 2023-12-15 15:58
@jimmylism it was actually an issue with VS Code: https://github.com/microsoft/vscode-jupyter/issues/14072

**Comment by jimmylism** [comment] 2023-12-15 16:09
Aha, thanks for letting us know!
